### PR TITLE
Restore call stack

### LINKED ISSUE #2: Live Variable Analysis
Which locations should be passed as arguments to `llvm.experimental.stackmap` and `llvm.experimental.patchpoint`?

### LINKED ISSUE #4: Stackmap Insertions
Stackmaps should be inserted everywhere they may be necessary, not just in the `trace` and `__unopt_trace` functions.

### LINKED ISSUE #6: Jumping to the Wrong Address
In `trace.c`, changing:

```
...
        uint64_t opt_location_value =
            stmap_get_location_value(sm, opt_rec.locations[i], r, bp);
        if (type == REGISTER) {
            uint16_t reg_num = unopt_rec.locations[i].dwarf_reg_num;
            uint64_t loc_size =
                stmap_get_location_value(sm, opt_rec.locations[i + 1], r, bp);
            memcpy(r + reg_num, &opt_location_value, loc_size);
...
```
to 
```
...
        uint64_t opt_location_value =
            stmap_get_location_value(sm, opt_rec.locations[i], r, bp);
            uint16_t reg_num = 0;
        if (type == REGISTER) {
            reg_num = unopt_rec.locations[i].dwarf_reg_num;
            uint64_t loc_size =
                stmap_get_location_value(sm, opt_rec.locations[i + 1], r, bp);
            memcpy(r + reg_num, &opt_location_value, loc_size);
...
```

causes the wrong address to be stored in the stack map.

### PR DESCRIPTION
**Pull request by gabi-250**
This introduces the code necessary to restore the state of each frame whenever a guard fails. This should also restore the register state.

To implement this, it was also necessary to:
* remove the `MachineFunctionPass` I'd implemented and modify the `emitPrologue` and `emitEpilogue` code in `lib/Target/X86/X86FrameLowering.cpp` to ensure each optimized function has the same stack size as its unoptimized version
* implement a crude version of live variable analysis in `CheckPointPass.cpp` (closes #2)
* insert a `stackmap` call after each call to a function defined in the module being processed (also implemented in `CheckPointPass`). This allows the runtime to obtain a record of all the locations that are live at each call site. The address of the stackmap is automatically recorded, which allows the runtime to work out the return addresses of the 'unoptimized' functions. (closes #4)

I've done my best to document my code, but I am aware it may not always be obvious what it does. Please let me know which parts are unclear/should be reimplemented.

(Also closes #6 as far as I can tell)

### CODE REVIEW

File: src/passes/function_passes/CheckPointPass.cpp [hunk 1]
```diff
@@ -12,179 +12,220 @@
...
   // stackmap calls inside each function with stackmap calls from the
-  // unoptimized version of the function
-  static std::map<StringRef, uint64_t> start_sm_id;
+  // unoptimized version of the function.
+  static map<StringRef, vector<uint64_t>> stackMaps;
 
   CheckPointPass() : FunctionPass(id) {}
 
+  virtual bool doInitialization(Module &mod) {
+    // Declare the guard failure function. This is necessary because the
```
Comment (vext01) [inline src/passes/function_passes/CheckPointPass.cpp]: So this is like an `extern` in C?

File: src/passes/function_passes/CheckPointPass.cpp [hunk 2]
```diff
@@ -12,179 +12,220 @@
...
-    // The callback to call when a guard fails
-    Constant* gf_handler_ptr = ConstantExpr::getBitCast(
+    // The callback to call when a guard fails.
+    Constant* guardHandler = ConstantExpr::getBitCast(
         mod->getFunction(GUARD_FUN_NAME), i8ptr_t);
     for (auto &bb : fun) {
       for (BasicBlock::iterator it = bb.begin(); it != bb.end(); ++it) {
-        if (isa<CallInst>(it) &&
-            cast<CallInst>(*it).getCalledFunction()->getName() == "putchar") {
+        if (funName.endswith("more_indirection") && isa<ReturnInst>(it)) {
```
Comment (vext01) [inline src/passes/function_passes/CheckPointPass.cpp]: There's a hardcoded function name in here. We should at least put an `XXX`.

File: src/passes/function_passes/CheckPointPass.cpp [hunk 3]
```diff
@@ -12,179 +12,220 @@
...
-          // trace; stackmap, if the current function is __unopt_trace
+          // optimized; stackmap, if the current function is unoptimized.
           Function *intrinsic = nullptr;
-          if (!fun_name.startswith(UNOPT_PREFIX)) {
-            // The current function is trace -> insert a patchpoint call. The
-            // arguments of the patchpoint call are: a callback, an integer
-            // which represents the number of arguments of the callback, and
-            // the arguments to pass to the callback.
+          if (!funName.startswith(UNOPT_PREFIX)) {
+            // The current function will optimized -> insert a patchpoint call.
```
Comment (vext01) [inline src/passes/function_passes/CheckPointPass.cpp]: `he current function will optimized`. Seems like a typo?

File: src/passes/function_passes/UnoptimizedCopyPass.cpp [hunk 4]
```diff
@@ -43,27 +44,33 @@ struct UnoptimizedCopyPass: public FunctionPass {
...
-            StringRef called_fun_name = called_fun->getName();
-            if (!called_fun_name.startswith(UNOPT_PREFIX)) {
-              // not an unoptimized function -> must call the unoptimized
-              // version of the function instead
-              Function *new_fun =
-                mod->getFunction(UNOPT_PREFIX + called_fun_name.str());
-              if (new_fun) {
-                call.setCalledFunction(new_fun);
+    auto funName = fun.getName();
+    if (funName == TRACE_FUN_NAME || funName == "more_indirection"
```
Comment (vext01) [inline src/passes/function_passes/UnoptimizedCopyPass.cpp]: Similarly here, add an `XXX`?

File: src/stackmap_checker/guard.c [hunk 5]
```diff
@@ -0,0 +1,350 @@
+#define UNW_LOCAL_ONLY
```
Comment (vext01) [inline src/stackmap_checker/guard.c]: Better add a license to new files.

Comment (vext01) [reply src/stackmap_checker/guard.c]: What does `UNW_LOCAL_ONLY` do?

File: src/stackmap_checker/guard.c [hunk 6]
```diff
@@ -0,0 +1,350 @@
...
+        unw_get_proc_name(&cursor, fun_name, sizeof(fun_name), &off);
+
+        // Stop when main is reached.
+        if (!strcmp(fun_name, "main")) {
+            break;
+        }
+
+        if (!registers[frame]) {
+            // 16 registers are saved for each frame
+            registers[frame] = calloc(16, sizeof(unw_word_t));
```
Comment (vext01) [inline src/stackmap_checker/guard.c]: Have you used valgrind on this code to check there are no memory errors?

File: src/stackmap_checker/guard.c [hunk 7]
```diff
@@ -0,0 +1,350 @@
...
+        unw_get_reg(&cursor, UNW_X86_64_RBP, &registers[frame][6]);
+        unw_get_reg(&cursor, UNW_X86_64_RSP, &registers[frame][7]);
+        unw_get_reg(&cursor, UNW_X86_64_R8,  &registers[frame][8]);
+        unw_get_reg(&cursor, UNW_X86_64_R9,  &registers[frame][9]);
+        unw_get_reg(&cursor, UNW_X86_64_R10, &registers[frame][10]);
+        unw_get_reg(&cursor, UNW_X86_64_R11, &registers[frame][11]);
+        unw_get_reg(&cursor, UNW_X86_64_R12, &registers[frame][12]);
+        unw_get_reg(&cursor, UNW_X86_64_R13, &registers[frame][13]);
+        unw_get_reg(&cursor, UNW_X86_64_R14, &registers[frame][14]);
+        unw_get_reg(&cursor, UNW_X86_64_R15, &registers[frame][15]);
```
Comment (vext01) [inline src/stackmap_checker/guard.c]: This is pretty neat. Good find with libunwind.

File: src/stackmap_checker/guard.c [hunk 8]
```diff
@@ -0,0 +1,350 @@
...
+        // Find address of the return address.
+        ret_addrs[frame] =
+            (uint64_t)((char *)registers[frame][UNW_X86_64_RBP] + 8);
```
Comment (vext01) [inline src/stackmap_checker/guard.c]: Why `char *`?

File: src/stackmap_checker/guard.c [hunk 9]
```diff
@@ -0,0 +1,350 @@
...
+    stack_size_record_t *unopt_size_rec =
+        stmap_get_size_record(sm, unopt_rec->index);
+    stack_size_record_t *opt_size_rec =
+        stmap_get_size_record(sm, opt_rec->index);
+    if (!unopt_size_rec || !opt_size_rec) {
+        errx(1, "Record not found.");
+    }
+
+    // Get the end address of the function in which a guard failed.
+    void *end_addr = get_sym_end((void *)opt_size_rec->fun_addr, "trace");
```
Comment (vext01) [inline src/stackmap_checker/guard.c]: Another hard-coded function name here?

File: src/passes/function_passes/CheckPointPass.cpp (hunk 1 above)
Comment (gabi-250) [reply src/passes/function_passes/CheckPointPass.cpp]: Yes, that is correct.

File: src/passes/function_passes/CheckPointPass.cpp (hunk 2 above)
Comment (gabi-250) [reply src/passes/function_passes/CheckPointPass.cpp]: I can do that, but the point is that a 'guard' is to going inserted at that particular point in the code. There is no real logic behind why I've chosen that particular condition.

File: src/passes/function_passes/CheckPointPass.cpp (hunk 3 above)
Comment (gabi-250) [reply src/passes/function_passes/CheckPointPass.cpp]: Well, this pass runs 'as early as possible', so at this point in time, both the `__unopt_` version and the regular versions are identical. So really, none of the functions are optimized at this time

File: src/passes/function_passes/UnoptimizedCopyPass.cpp (hunk 4 above)
Comment (gabi-250) [reply src/passes/function_passes/UnoptimizedCopyPass.cpp]: Can do, but it is probably best to remove everything after `||`. The only function we really **don't** want inlined is `trace`. I disabled all inlining to test my code, that's why there are some hardcoded values here and there.

File: src/stackmap_checker/guard.c (hunk 6 above)
Comment (gabi-250) [reply src/stackmap_checker/guard.c]: Yes, I have.

File: src/stackmap_checker/guard.c (hunk 8 above)
Comment (gabi-250) [reply src/stackmap_checker/guard.c]: Ah, you're right, it's unnecessary.

File: src/stackmap_checker/guard.c (hunk 5 above)
Comment (gabi-250) [reply src/stackmap_checker/guard.c]: It is supposed to run an optimized version of `libunwind`:

```
However, if you tell libunwind that your program only needs local unwinding, then a special implementation can be selected which may run much faster than the generic implementation which supports both kinds of unwinding. To select this optimized version, simply define the macro UNW_LOCAL_ONLY before including the headerfile <libunwind.h>.
```

File: src/passes/function_passes/CheckPointPass.cpp [hunk 10]
```diff
@@ -12,179 +12,220 @@
...
 namespace {
 
 /*
- * Insert a stackmap call before each call to `putchar`.
+ * Insert a `stackmap` call after each call to record its return address.
  *
- * This only runs on `trace` and `__unopt_trace`. All other functions are
- * ignored.
+ * The unoptimized version of each function contains the same number of
+ * `llvm.experimental.stackmap` calls as the original version. Knowing the
```
[the remark this answers is not in the document]
Comment (gabi-250) [reply src/passes/function_passes/CheckPointPass.cpp]: The 'original' version is the user-defined function. The other function pass creates an `__unopt_` version of each user-defined function, which I call the 'unoptimized' version.

**Comment by gabi-250** [comment]
@vext01 Thank you for your review! I think I've addressed all your comments, except for the one regarding the license. I haven't added a license to any of the files yet, but I will do before this PR is merged.

File: src/stackmap_checker/guard.c (hunk 5 above)
Comment (vext01) [reply src/stackmap_checker/guard.c]: OK. I wonder what "non-local" unwinding would mean?

File: src/stackmap_checker/guard.c (hunk 6 above)
Comment (vext01) [reply src/stackmap_checker/guard.c]: Good job!

**Comment by vext01** [comment]
You can do licenses in a separate PR if you like.

Ready to squash?

**Comment by gabi-250** [comment]
@vext01 Sure. Is there nothing else you'd like changed? I am aware this is hard to review and that my code isn't that well written, but please **do** let me know if you see anything awfully wrong with it!

File: src/stackmap_checker/guard.c (hunk 5 above)
Comment (gabi-250) [reply src/stackmap_checker/guard.c]: I think anything outside of the current compilation unit is 'non-local', but it's just a guess.

**Comment by gabi-250** [comment]
If not, this is squashed and ready to merge.

**Comment by vext01** [comment]
I'd be here all for days doing a deep review of these changes. I'm good to merge so you can continue.
