### PR TITLE
Fix ret addrs

### LINKED ISSUE #12: Return Addresses
The return address is supposed to be `0x40313f`, but the `stackmap` call generated for `__unopt_get_number` is at `0x403141`.

```
11│    0x0000000000403137 <+23>:    mfence
12│    0x000000000040313a <+26>:    callq  0x403120 <__unopt_get_number>
13│    0x000000000040313f <+31>:    mov    %eax,%ebx
14│    0x0000000000403141 <+33>:    mfence
15│    0x0000000000403144 <+36>:    mov    %ebx,-0xc(%rbp)
```

### PR DESCRIPTION
**Pull request by gabi-250**
Please review  #15  first.

This closes #12.

The previous implementation of `CheckPointPass` inserted a `stackmap` call after each call instruction, in order to have the function's return address stored as a stack map record (`stackmap` calls always have their addresses recorded in a stack map record). This approach didn't work, because at machine instruction level, the original call and the `stackmap` call are not necessarily adjacent (other instructions may be inserted in between).

The current implementation is inspired by this discussion: http://llvm.1065342.n5.nabble.com/llvm-dev-Figuring-out-return-address-of-a-call-td106617.html

Each function call is replaced by a `patchpoint` call. A call to `llvm.experimental.patchpoint` emits a call to the specified callback, which, in this case, is the function whose return address needs to be recorded.

### CODE REVIEW

**Comment by gabi-250** [comment]
@vext01 I've just realized this prevents all functions from being inlined.

**Comment by vext01** [comment]
OK, I'll wait for your word on reviewing this then.

**Comment by vext01** [comment]
What's the status of this on @gabi-250?

**Comment by gabi-250** [comment]
@vext01 This should be ready for review, I made a slight change yesterday after a discussion I had with Laurie.

**Comment by vext01** [comment]
Can you give a short synopsis on the outcome of that conversation, and how it relates to your comment last week about it disabling inlining? Presumably that's not a problem any more, or?

**Comment by gabi-250** [comment]
Laurie wanted inlining to happen, at least in the optimized functions. I initially wrapped all calls in `patchpoint` calls, which inhibits inlining. My initial implementation of `CheckPointPass` inserted a `stackmap` call after each call instruction, which sometimes resulted in the wrong 'return address' being stored in the stack map. The current approach inserts a `stackmap` call after each call instruction in the optimized functions, and replaces calls in the unoptimized functions with `patchpoint` calls. As far as I can tell, this never causes control to jump to the wrong address, and inlining *can* happen in the optimized functions.

File: src/passes/function_passes/CheckPointPass.cpp [hunk 1]
```diff
@@ -104,30 +105,68 @@ struct CheckPointPass: public FunctionPass {
...
-                                         builder.getInt32(13)  // XXX shadow
+                                         builder.getInt32(13)
                                        };
-            auto liveVariables = getLiveRegisters(*it);
-            std::move(liveVariables.begin(), liveVariables.end(),
-                      std::back_inserter(args));
-            auto intrinsic = Intrinsic::getDeclaration(
-                mod, Intrinsic::experimental_stackmap);
-            auto call_inst = builder.CreateCall(intrinsic, args);
+            if (funName.startswith(UNOPT_PREFIX)) {
```
Comment (vext01) [inline src/passes/function_passes/CheckPointPass.cpp]: I'm finding this block of code a little opaque. Would it benefit from some comments?

File: src/passes/function_passes/LiveVariablesPass.cpp [hunk 2]
```diff
@@ -0,0 +1,153 @@
...
+            // the variables live at this point.
+            auto liveVariables = getLiveRegisters(*it);
+            vector<Value *> args(callInst.arg_begin(), callInst.arg_end());
+            // Pass the live locations to the stackmap/patchpoint call. This
+            // also inserts the size of each 'live' location into the stackmap.
+            std::move(liveVariables.begin(), liveVariables.end(),
+                      std::back_inserter(args));
+            CallInst *newCall = CallInst::Create(calledFun, args);
+            if (!callInst.use_empty()) {
+              callInst.replaceAllUsesWith(newCall);
```
Comment (vext01) [inline src/passes/function_passes/LiveVariablesPass.cpp]: OK, so this code just mutates the arguments to your stackmap calls to add the live vars?

File: src/passes/function_passes/LiveVariablesPass.cpp [hunk 3]
```diff
@@ -0,0 +1,153 @@
...
+    auto patchpointIntrinsici64 = Intrinsic::getDeclaration(
+        mod, Intrinsic::experimental_patchpoint_i64);
+    return fun == stackmapIntrinsic || fun == patchpointIntrinsicVoid
+        || fun == patchpointIntrinsici64;
+  }
+
+  /*
+   * Return the list of registers which are live across the given instruction.
+   */
+  static vector<Value *> getLiveRegisters(Instruction &instr) {
```
Comment (vext01) [inline src/passes/function_passes/LiveVariablesPass.cpp]: This code was just moved, right?

File: src/passes/function_passes/UnoptimizedCopyPass.cpp [hunk 4]
```diff
@@ -74,6 +86,15 @@ struct UnoptimizedCopyPass: public FunctionPass {
     }
     return true;
   }
+
+  static bool isPatchpoint(Function *fun) {
```
Comment (vext01) [inline src/passes/function_passes/UnoptimizedCopyPass.cpp]: This code is very similar to some code above. Can it be modularised?

File: src/stackmap_checker/stmap.c [hunk 5]
```diff
@@ -145,8 +153,8 @@ stack_map_record_t* stmap_get_last_record(stack_map_t *sm,
     return last_rec;
 }
 
-stack_map_pos_t* stmap_get_unopt_return_addr(stack_map_t *sm, uint64_t return_addr)
-{
+ stack_map_pos_t* stmap_get_unopt_return_addr(stack_map_t *sm, uint64_t return_addr)
```
Comment (vext01) [inline src/stackmap_checker/stmap.c]: Indent intentional?

File: src/stackmap_checker/stmap.c [hunk 6]
```diff
@@ -190,11 +198,11 @@ stack_map_record_t* stmap_first_rec_after_addr(stack_map_t *sm, uint64_t addr)
             stmap_get_last_record(sm, *size_rec);
         uint64_t last_addr = size_rec->fun_addr + last_rec->instr_offset;
         if (addr > last_addr) {
-            continue;
-        }
+             continue;
```
Comment (vext01) [inline src/stackmap_checker/stmap.c]: All of these indents are correct?

File: src/tests/support.py [hunk 7]
```diff
@@ -0,0 +1,19 @@
+import os
```
Comment (vext01) [inline src/tests/support.py]: Do you need to sync the branch?

**Comment by vext01** [comment]
A few comments, but again, not a particularly deep review. You are now clearly the expert on this work!

File: src/passes/function_passes/LiveVariablesPass.cpp (hunk 3 above)
Comment (gabi-250) [reply src/passes/function_passes/LiveVariablesPass.cpp]: That is right.

File: src/tests/support.py (hunk 7 above)
Comment (gabi-250) [reply src/tests/support.py]: I don't think that is necessary, since we merged the tests branch into this one (not into master).

File: src/passes/function_passes/LiveVariablesPass.cpp (hunk 2 above)
Comment (gabi-250) [reply src/passes/function_passes/LiveVariablesPass.cpp]: Yep, that's pretty much it.

**Comment by gabi-250** [comment]
@vext01 I think I've addressed your comments. Let me know if there is anything else you'd like changed.

File: src/tests/support.py (hunk 7 above)
Comment (vext01) [reply src/tests/support.py]: oh! I didn't realise that.

In future we probably want to merge into master unless there's a good reason.

File: src/passes/function_passes/CheckPointPass.cpp [hunk 8]
```diff
@@ -163,6 +172,11 @@ struct CheckPointPass: public FunctionPass {
               }
               ReplaceInstWithInst(&oldCallInst, callInst);
             } else {
+              // The function is not an __unopt_ function. Insert a  stackmap
+              // call after the call instruction at `it` to record the return
```
Comment (vext01) [inline src/passes/function_passes/CheckPointPass.cpp]: `it`?

File: src/passes/function_passes/Utils/Utils.cpp [hunk 9]
```diff
@@ -0,0 +1,29 @@
+#include "Utils.h"
+
+using namespace llvm;
+
+bool isPatchpoint(Function *fun) {
```
Comment (vext01) [inline src/passes/function_passes/Utils/Utils.cpp]: Ah, let me clarify what I meant. Perhaps you can merge these two functions by having them return a bit field encoding the three possibilities?

**Comment by vext01** [comment]
Sorry, a couple more comments.

File: src/passes/function_passes/CheckPointPass.cpp (hunk 8 above)
Comment (gabi-250) [reply src/passes/function_passes/CheckPointPass.cpp]: The current iterator. I'll make the comment clearer.

**Comment by gabi-250** [comment]
@vext01 I tried merging the two functions, but this somehow feels even worse than my previous implementation. Let me know what you think.

File: src/passes/function_passes/Utils/Utils.cpp [hunk 10]
```diff
@@ -2,28 +2,17 @@
...
   auto stackmapIntrinsic = Intrinsic::getDeclaration(
       mod, Intrinsic::experimental_stackmap);
   auto patchpointIntrinsicVoid = Intrinsic::getDeclaration(
       mod, Intrinsic::experimental_patchpoint_void);
   auto patchpointIntrinsici64 = Intrinsic::getDeclaration(
       mod, Intrinsic::experimental_patchpoint_i64);
-  return fun == stackmapIntrinsic || fun == patchpointIntrinsicVoid
-      || fun == patchpointIntrinsici64;
+  unsigned int type = 0;
+  type |= (fun == stackmapIntrinsic);
```
Comment (vext01) [inline src/passes/function_passes/Utils/Utils.cpp]: I'd have tried to use the macros you defined here, rather than use magic numbers.

**Comment by gabi-250** [comment]
@vext01 Something like that?

**Comment by vext01** [comment]
Can't more than one of the bits be set simultaneously?

**Comment by gabi-250** [comment]
@vext01 No, the called function can only be one of `llvm.experimental.stackmap`, `llvm.experimental.patchpoint_void`, `llvm.experimental.patchpoint_i64`

**Comment by vext01** [comment]
Yes, I've led you astray. My apologies. You might as well have a function which returns one of three defined integers in that case, right?

Sorry about this. Misunderstanding on my part.

**Comment by gabi-250** [comment]
@vext01 Simply returning one of the constants would work, but it would make this [condition]( https://github.com/gabi-250/llvm-playground/blob/a21329e95e69c2ca32855ee22e6b595a00bf0ba7/src/passes/function_passes/LiveVariablesPass.cpp#L50)
a bit harder to read. I am happy with the current implementation, but let me know if you think it has any serious faults.

**Comment by vext01** [comment]
I think I'll let you take this decision :)

Apparently I'm having "one of those days" (tm).

**Comment by gabi-250** [comment]
@vext01 Okay, then I think this should be good to merge after I squash :)

**Comment by vext01** [comment]
squash away

**Comment by gabi-250** [comment]
@vext01 squashed!
